### ISSUE TITLE
Unable to get it work under ubuntu 15.04

### ISSUE THREAD

**Issue by johnr14** [rrthomas/cw#10]
I followed the procedure in the README, but I can't find how to fix it.
I use this in my path : /usr/local/lib/luarocks/rocks/cw/2.0.1-2/libexec/cw

Here is the output of df
/usr/bin/lua5.1: /usr/local/lib/luarocks/rocks/cw/2.0.1-2/bin/cw:141: attempt to                                                     call field 'pipeline_iterator' (a nil value)
stack traceback:
        /usr/local/lib/luarocks/rocks/cw/2.0.1-2/bin/cw:141: in main chunk
        [C]: ?

Thanks

**Comment by rrthomas** [comment]
I don't support that version any more, so I've deleted the rock from luarocks.org. Thanks very much for the bug report. You'll find if you try to install cw again that you'll now need Lua 5.2.
