### ISSUE TITLE
License upgraded to GPLv3+, but the LICENSE file is still GPLv2

### ISSUE THREAD

**Issue by solbu** [rrthomas/cw#11]
In 2013 you upgraded the license from GPLv2+ to GPLv3+.
But you forgot to upgrade the LICENSE file that contains the actuall license text, which is still GPLv2.
You might want to fix that,

I package cw for Mageia, and just now discovered that you have continued the development.
Thank you for that. :-)

**Comment by rrthomas** [comment]
Thanks for noticing this; I have updated the file and released version 2.0.6.
