### ISSUE TITLE
/usr/bin/lua: /usr/bin/cw:39: module 'std' not found:

### ISSUE THREAD

**Issue by solbu** [rrthomas/cw#12]
Hi, Thomas.

I am the Mageia cw maintainer, and I can't get the new lua based version to work. I stumbled across your fork a few days ago, and I'm attempting to upgrade our old 1.0.16 version. 
We have a policy that all software must be compiled from the source code, so No «rock» installation.

Apparently it can't find the std module, but seaches for the module yields absolutely no relevant results of any kind, and there is no list of dependencies in the documentaiton.

When I run «cw --help», I get this output:
```
$ cw --help
/usr/bin/lua: /usr/bin/cw:39: module 'std' not found:
        no field package.preload['std']
        no file '/usr/share/lua/5.2/std.lua'
        no file '/usr/share/lua/5.2/std/init.lua'
        no file '/usr/lib/lua/5.2/std.lua'
        no file '/usr/lib/lua/5.2/std/init.lua'
        no file '/usr/lib64/lua/5.2/std.lua'
        no file '/usr/lib64/lua/5.2/std/init.lua'
        no file '/usr/lib/lua/5.2/std.so'
        no file '/usr/lib/lua/5.2/loadall.so'
        no file '/usr/lib64/lua/5.2/std.so'
        no file '/usr/lib64/lua/5.2/loadall.so'
        no file './std.so'
stack traceback:
        [C]: in function 'require'
        /usr/bin/cw:39: in main chunk
        [C]: in ?
```

**Comment by solbu** [comment]
If we can't get this to work, we are dropping it from the next Mageia release.

**Comment by rrthomas** [comment]
All the dependencies are listed in the "dependencies" section of `rockspecs.lua`.

**Comment by lparsons** [comment]
I run into the same issue, I have luarocks installed via linuxbrew. I've installed stdlib via `luarocks install stdlib` but I still get this error. Any advice?

**Comment by rrthomas** [comment]
@lparsons: install cw via luarocks.

Closing the issue, as I don't see an actual problem here.

**Comment by lparsons** [comment]
Sorry, I wasn't clear. I installed luarocks using linuxbrew. Then I used luarocks to install `cw`. That is when I ran into the issue. In an attempt to fix it, I tried using luarocks to install stdlib, but that didn't fix anything.

**Comment by rrthomas** [comment]
@lparsons, most likely a problem with your linuxbrew setup. Linuxbrew's luarocks package should set up the `lua` it uses suitably.
