### ISSUE TITLE
strace-color binary does not color

### ISSUE THREAD

**Issue by flip111** [rrthomas/cw#14]
I saw that a binary `strace-color` was installed at exact the same time as i installed `cw`, so i assume it belongs to this package.

I tried to put this in my `~/.zshrc`

```bash
if [ -n "$PS1" ]; then PATH=$(~/.luarocks/bin/cw-definitions-path):$PATH; export PATH; fi
```

I also tried setting `PATH` per process
```
PATH=$(~/.luarocks/bin/cw-definitions-path):$PATH; ~/.luarocks/bin/strace-color ~/php/php-src_7.4.4/install/bin/php -S localhost:8002  --php-ini php_debug.ini
```

In both situations i can do `echo $PATH` and see that the first path points to `/home/flip111/.luarocks/lib/luarocks/rocks/cw/2.0.6-1/libexec/cw`. In this directory i find the cw definition files.

I don't see any color output of strace, did i do something wrong ?

**Comment by rrthomas** [comment]
Just tested and it works for me. Perhaps the version of strace you're using doesn't match the patterns in the definition?

**Comment by flip111** [comment]
```
» strace -V
strace -- version 4.26
Copyright (c) 1991-2018 The strace developers <https://strace.io>.
```

some output
```
write(6, "                      -> lexer_6"..., 145) = 145
mmap(NULL, 2097152, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7ff08e200000
brk(0x55eed8bf7000)                     = 0x55eed8bf7000
```

I see in the definition files what i think are regular expressions. Here the biggest one:

    %(.+%).*[ ]=[ ]

Options: Case sensitive; Exact spacing; Dot doesn’t match line breaks; ^$ don’t match at line breaks; Greedy quantifiers; Regex syntax only

* Match the character “%” literally `%`
* Match the regex below and capture its match into backreference number 1 `(.+%)`
    * Match any single character that is NOT a line break character (line feed) `.+`
        * Between one and unlimited times, as many times as possible, giving back as needed (greedy) `+`
    * Match the character “%” literally `%`
* Match any single character that is NOT a line break character (line feed) `.*`
    * Between zero and unlimited times, as many times as possible, giving back as needed (greedy) `*`
* Match the character “ ” literally `[ ]`
* Match the character “=” literally `=`
* Match the character “ ” literally `[ ]`

---

There are no percentage signs in the trace output. Not sure how this is supposed to work.

**Comment by rrthomas** [comment]
These are Lua regexps; please see the Lua manual!

**Comment by flip111** [comment]
I don't know about lua regex, i was just trying to think along to solve this issue.

**Comment by rrthomas** [comment]
I had a look at your sample output, and at mine (which is coloured), and I can't see any reason why yours wouldn't match the regex. "%" is the Lua regex escape, so "%(" means a literal "(", for example. So what should be coloured is from an open paren to the space after an equals sign.

Hence, I would check whether you're really using `strace-color`, not `strace`.

**Comment by flip111** [comment]
This is also interesting ... `which strace-color` gives the following:

```bash
/home/flip111/.luarocks/lib/luarocks/rocks/cw/2.0.6-1/libexec/cw/strace-color
```

And when running
```
» strace-color /home/flip111/php/php-src_7.4.4/install/bin/php -S localhost:8002  --php-ini php_debug.ini
/usr/bin/lua5.3: .../flip111/.luarocks/lib/luarocks/rocks/cw/2.0.6-1/bin/cw:39: module 'std' not found:
	no field package.preload['std']
	no file '/usr/local/share/lua/5.3/std.lua'
	no file '/usr/local/share/lua/5.3/std/init.lua'
	no file '/usr/local/lib/lua/5.3/std.lua'
	no file '/usr/local/lib/lua/5.3/std/init.lua'
	no file '/usr/share/lua/5.3/std.lua'
	no file '/usr/share/lua/5.3/std/init.lua'
	no file './std/init.lua'
	no file '/usr/local/lib/lua/5.3/std.so'
	no file '/usr/lib/x86_64-linux-gnu/lua/5.3/std.so'
	no file '/usr/lib/lua/5.3/std.so'
	no file '/usr/local/lib/lua/5.3/loadall.so'
	no file './std.so'
stack traceback:
	[C]: in function 'require'
	.../philippe/.luarocks/lib/luarocks/rocks/cw/2.0.6-1/bin/cw:39: in main chunk
	[C]: in ?
```

However like before
```bash
~/.luarocks/bin/strace-color ~/php/php-src_7.4.4/install/bin/php -S localhost:8002  --php-ini php_debug.ini
```

gives just strace without color. In this last case i'm "really" using `strace-color`. But no i start to ask myself ... which strace-color is the right one ?

**Comment by rrthomas** [comment]
Excellent detective work! I now see what is going wrong, I think.

The `strace-color` you want to run is the first one. The second one is just a redirection to `strace`, and it should be run by `cw`. I suspect the second one has got in your `PATH` ahead of the first.

However, there seems to be something wrong with your setup. Running `strace-color` should run the first one, as I said, which should have a `#!` line that calls `cw`, setting up the Lua paths so that `std` is found correctly. What happens if you just run `cw --help`?

**Comment by flip111** [comment]
> I suspect the second one has got in your `PATH` ahead of the first.

```bash
~/.luarocks/bin/strace-color ~/php/php-src_7.4.4/install/bin/php -S localhost:8002  --php-ini php_debug.ini
```

is not in path, i was supplying the full directory to the executable.

---

```bash
» cw --help
zsh: command not found: cw
» ~/.luarocks/bin/cw --help
Usage: cw [OPTION]... [FILE]...

Not for direct use (see cw(1)).

Options:

      --help               display this help, then exit
      --version            display version information, then exit
```

`strace-color` is in PATH because i added this to `~/.zshrc`
```
if [ -n "$PS1" ]; then PATH=$(~/.luarocks/bin/cw-definitions-path):$PATH; export PATH; fi
```

But `cw` is not in path because `~/.luarocks/bin/cw-definitions-path` prints `/home/flip111/.luarocks/lib/luarocks/rocks/cw/2.0.6-1/libexec/cw` which does not contain `cw`

**Comment by flip111** [comment]
It's solved now !

The issue was that luarocks didn't see package that were installed as user, see other issue https://github.com/rrthomas/cw/issues/13#issue-599576219

To fix this i had to add `eval $(luarocks path --bin)` to `~/.zshrc`, see https://github.com/luarocks/luarocks/wiki/Using-LuaRocks#rocks-trees-and-the-lua-libraries-path

In total i have now the following commands to make it all work on ubuntu 19.10

```bash
sudo apt install luarocks liblua5.3-dev
install with luarocks install cw --local
```

Add to `~/.zshrc` or `~/.bashrc`
```bash
eval $(luarocks path --bin)
if [ -n "$PS1" ]; then PATH=$(~/.luarocks/bin/cw-definitions-path):$PATH; export PATH; fi
```

Then open a new shell and confirm that `which strace-color` points to a directory similar to `~/.luarocks/lib/luarocks/rocks/cw/2.0.6-1/libexec/cw`

**Comment by rrthomas** [comment]
Glad you sorted it! I just spent a while reinstalling LuaRocks because my installation was out of date and also I had installed cw from source rather than as a rock, so I wanted to check that I wasn't getting a "magic system" effect. In fact, it all works for me too!
